version: '3'

services: 

  laravel:
    build:
      context: ./laravel
      dockerfile: dockerfile.prod
    image: edallgallo/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile.prod
    image: edallgallo/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge     